# Site settings
title: sarhov || FrontEnd And Web Developer
email: sarhov@sarhov.com
phone: +374 94 77 33 02
skype: sarhov  
description:  sarhov is a profesional frontend and web developer.
second_description:  In now I am doing my own projects,  but  if you want, then you always can touch with me, I am always open for new projects.
avatar: http://sarhov.com/img/avatar.svg
baseurl: "http://sarhov.com/" # the subpath of your site, e.g. /blog/
url: "http://sarhov.com" # the base hostname & protocol for your site
socials:
- title: facebook
  url: http://fb.com/sarhov
- title: github
  url: http://github.com/sarhov

# Build settings
markdown: kramdown
collections:
  works:
    output: true
    permalink: /works/:path/
  my_projects:
    output: true
    permalink: /my_projects/:path/
