# Site settings
avatar: https://sarhov.com/img/avatar.png
baseurl: "https://sarhov.com/" # the subpath of your site, e.g. /blog/
url: "https://sarhov.com" # the base hostname & protocol for your site
socials:
- title: facebook
  url: https://fb.com/sarhov
  icon: sarhov-facebook
- title: github
  url: https://github.com/sarhov
  icon: sarhov-github
highlighter: rouge
permalink: /:title/
# Build settings
markdown: kramdown
# collections:
#   works:
#     output: true
#     permalink: /works/:path/
#   my_projects:
#     output: true
#     permalink: /my_projects/:path/
