# Site settings
avatar: http://sarhov.com/img/avatar.png
baseurl: "http://sarhov.com/" # the subpath of your site, e.g. /blog/
url: "http://sarhov.com" # the base hostname & protocol for your site
socials:
- title: facebook
  url: http://fb.com/sarhov
  icon: sarhov-facebook
- title: github
  url: http://github.com/sarhov
  icon: sarhov-github

# Build settings
markdown: kramdown
# collections:
#   works:
#     output: true
#     permalink: /works/:path/
#   my_projects:
#     output: true
#     permalink: /my_projects/:path/
